services:
  getanymessage:
    image: hub.madelineproto.xyz/danog/madelineproto
    restart: always
    init: true
    tty: true
    working_dir: /app/src
    volumes:
      - ./:/app
    command: php /app/src/bot.php
